### ISSUE TITLE
The app deployment does not wait the database to be up before starting

### ISSUE THREAD

**Issue by jromelague** [promyze/helm-charts#10]
Hi,

When we use the the bitnami mongodb chart to deploy the database with the promyze chart, most of the times on the first deployment the server is inavailable
![image](https://github.com/promyze/helm-charts/assets/103044506/f4984748-3486-4c85-91e3-a92e644d6ce4)
Here is the app deployment pod logs
`{"level":"info","message":"Default database configs","label":"server","timestamp":"Wed, 26 Jul 2023 15:44:50 GMT"}
mongoose: Cannot specify a custom index on `_id` for model name "View", MongoDB does not allow overwriting the default `_id` index. See http://bit.ly/mongodb-id-index
{"level":"info","message":"********** Node server is starting up **********","label":"server","timestamp":"Wed, 26 Jul 2023 15:44:51 GMT"}
{"level":"info","message":"Instantiate mongoose connection","label":"server","timestamp":"Wed, 26 Jul 2023 15:44:51 GMT"}
{"poolSize":10,"useCreateIndex":true,"useFindAndModify":false,"useNewUrlParser":true,"useUnifiedTopology":true}
{"level":"info","message":"Attempt to connect to custom database","label":"server","timestamp":"Wed, 26 Jul 2023 15:44:51 GMT"}
{"level":"info","message":"Production mode","label":"server","timestamp":"Wed, 26 Jul 2023 15:44:51 GMT"}
(node:1) DeprecationWarning: collection.remove is deprecated. Use deleteOne, deleteMany, or bulkWrite instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
{"level":"info","message":"Connection to custom database OK","label":"server","timestamp":"Wed, 26 Jul 2023 15:44:51 GMT"}
{"level":"info","message":"Connection to custom mongo database successful","label":"server","timestamp":"Wed, 26 Jul 2023 15:44:51 GMT"}
{"level":"info","message":"Authentication service configuration set with environnement variables for service : active-directory","label":"server","timestamp":"Wed, 26 Jul 2023 15:44:52 GMT"}
{"level":"info","message":"Instantiate routes and models","label":"server","timestamp":"Wed, 26 Jul 2023 15:44:52 GMT"}
{"level":"info","message":"Start Core Events Controller","label":"server","timestamp":"Wed, 26 Jul 2023 15:44:52 GMT"}
{"_id":"NEW_PERIOD_FOR_PROJECTS","_delay":43200000,"_timer":null,"level":"info","message":"Add new notification scenario: ","label":"server","timestamp":"Wed, 26 Jul 2023 15:44:52 GMT"}
{"_id":"REPORT_SENDER","_delay":86400000,"_timer":null,"_dateOfExecution":1690437600000,"level":"info","message":"Add new notification scenario: ","label":"server","timestamp":"Wed, 26 Jul 2023 15:44:52 GMT"}
{"level":"info","message":"Starting express app","label":"server","timestamp":"Wed, 26 Jul 2023 15:44:52 GMT"}
{"level":"info","message":"Disable Socket In Production","label":"server","timestamp":"Wed, 26 Jul 2023 15:44:52 GMT"}
{"level":"info","message":"Express server listening on port 3000","label":"server","timestamp":"Wed, 26 Jul 2023 15:44:52 GMT"}
{"level":"info","message":"Execute patch THEM-2889_RENAME_CRAFT_TAG_FROM_PLUGIN_VALIDATED_FIELD","label":"server","timestamp":"Wed, 26 Jul 2023 15:44:52 GMT"}
{"level":"info","message":"Schedule job : ACTION_PLANS_SUGGESTIONS next invoke will be at Thu Jul 27 2023 08:00:00 GMT+0000","label":"server","timestamp":"Wed, 26 Jul 2023 15:44:53 GMT"}
{"level":"info","message":"Schedule job : AUTH_SCHEDULER next invoke will be at Thu Jul 27 2023 08:00:00 GMT+0000","label":"server","timestamp":"Wed, 26 Jul 2023 15:44:53 GMT"}
{"level":"info","message":"Schedule job : ADD_PERIOD_FOR_EACH_PERIODICITY_IF_NEEDED next invoke will be at Thu Jul 27 2023 08:00:00 GMT+0000","label":"server","timestamp":"Wed, 26 Jul 2023 15:44:53 GMT"}
{"level":"info","message":"Schedule job : SCAN_ALL_PROJECT_AND_ADD_AUTOMATIC_PROCESS_GOAL_PLAN_IF_NEEDED next invoke will be at Thu Jul 27 2023 08:00:00 GMT+0000","label":"server","timestamp":"Wed, 26 Jul 2023 15:44:53 GMT"}
{"level":"info","message":"Schedule job : SCAN_ALL_PROCESS_GOAL_PLAN_AND_APPROVE_IT_IF_NEEDED next invoke will be at Thu Jul 27 2023 08:00:00 GMT+0000","label":"server","timestamp":"Wed, 26 Jul 2023 15:44:53 GMT"}
{"level":"info","message":"Schedule job : SEND_CRAFT_TAG_GOAL_REMINDER next invoke will be at Thu Jul 27 2023 08:00:00 GMT+0000","label":"server","timestamp":"Wed, 26 Jul 2023 15:44:53 GMT"}
{"level":"info","message":"Execute patch THEM-2890_VALIDATE_CRAFT_TAGS_FROM_OLD_CRAFT_WORKSHOP_SESSIONS","label":"server","timestamp":"Wed, 26 Jul 2023 15:44:53 GMT"}
{"level":"info","message":"Execute patch THEM-2891_PUT_CRAFT_TAGS_REVIEWED_IN_CRAFT_TAGS_VALIDATED_ATTRIBUTE_IN_CRAFT_WORKSHOP_SESSIONS","label":"server","timestamp":"Wed, 26 Jul 2023 15:44:53 GMT"}
{"level":"info","message":"Execute patch THEM-2892_SYNC_CRAFT_WORKSHOP_SESSION_INDEXES","label":"server","timestamp":"Wed, 26 Jul 2023 15:44:53 GMT"}
(node:1) DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use Collection.countDocuments or Collection.estimatedDocumentCount instead
{"level":"info","message":"Execute patch THEM-2893_CREATE_CRAFT_WORKSHOP_SESSION_IN_SPACES","label":"server","timestamp":"Wed, 26 Jul 2023 15:44:53 GMT"}
{"level":"info","message":"Execute patch THEM-2895_PRACTICES_DESCRIPTIONS_HTML_TO_MARKDOWN","label":"server","timestamp":"Wed, 26 Jul 2023 15:44:53 GMT"}
{"level":"info","message":"Execute patch THEM-2896","label":"server","timestamp":"Wed, 26 Jul 2023 15:44:53 GMT"}
{"level":"info","message":"Execute patch THEM-2897","label":"server","timestamp":"Wed, 26 Jul 2023 15:44:53 GMT"}
{"level":"info","message":"Execute patch THEM-2898_REMOVE_VECTOR_FEATURE_SUGGESTION","label":"server","timestamp":"Wed, 26 Jul 2023 15:44:53 GMT"}
{"level":"info","message":"Execute patch THEM-2899_CONVERT_PRACTICE_STRING_CATEGORIES_TO_ENTITIES","label":"server","timestamp":"Wed, 26 Jul 2023 15:44:53 GMT"}
{"level":"info","message":"Execute patch THEM-2900_CREATE_EXAMPLE_SKILLS_FOR_CRAFT_TAGS_SET","label":"server","timestamp":"Wed, 26 Jul 2023 15:44:53 GMT"}
{"level":"info","message":"Execute patch THEM-2901_SET_MOST_USED_CATEGORIES_AS_EXPERTISES","label":"server","timestamp":"Wed, 26 Jul 2023 15:44:53 GMT"}`

If we scale down / up the app deployment, the server becomes available.
It seems like the database if not fully initialized when the connection is done.

Best regards,
Jérôme.

**Comment by cteyton** [comment]
Hello Jérôme,
Thanks for reporting this issue. 
Sorry for the delay, holidays went there ;)
We'll check on that these following days, and I'll let you know.

**Comment by cteyton** [comment]
Hello Jérôme,

Btw, I might be wrong but it seems that the oldest available Bitnami MongoDB Chart starts for MongoDB 5.x, but currently, Promyze is available only on MongoDB 4.x. We do not guarantee that it'll work on MongoDB 5.x.
We have this task in [our backlog](https://roadmap.promyze.com/45).

**Comment by jromelague** [comment]
Hi Cédric,

We are using the 13.6.0 Bitnami MongoDB chart version with the `4.4-debian-10` tag for MongoDB image.

**Comment by cteyton** [comment]
Ok thanks Jérôme.
Do you confirm you run this Chart as a dependency?

As a workaround, we're likely to add an initContainer that waits a few seconds (sleep).  It might be a quick-win strategy.

In a second time, we'll add an initContainers that will be only dedicated to testing the Database Connection and exits if everything is fine, with a restart policy on the pod.

**Comment by jromelague** [comment]
Yes we run this chart as a dependency.
Your strategy sounds good for me.

**Comment by cteyton** [comment]
@jromelague hope this will help :)
