### ISSUE TITLE
The 0.4.0 chart still references 4.12.1 application version instead of 4.13.0

### ISSUE THREAD

**Issue by jromelague** [promyze/helm-charts#15]
Hi,

The 0.4.0 chart still references image tag 4.12.1 application version instead of 4.13.0.
Can you publish a new chart version to update the images tag ? (I see that this correction has already been committed on the main branch)

Best regards.

**Comment by cteyton** [comment]
hi @jromelague 
Sorry for the delay, this has been fixed in the 0.4.1 release thanks to commit #189688eaffeed693871bff86a97d08ca83eec963
