### ISSUE TITLE
Allow to add labels on Promyze deployments, labels and annotations on Promyze services

### ISSUE THREAD

**Issue by pbq** [promyze/helm-charts#16]
Hi, 
is it possible to add `labels` to Promyze deployments ? 
and to add `labels` and `annotations` to services ?

We have some restrictive Kyverno controls on labels and annotations and I would prefer not to patch the Promyze Helm.

Thank you!

Best regards,
Pierre

**Comment by cteyton** [comment]
Hi @pbq 
It's indeed possible from the 0.4.1 version of the Chart to add annotations to deployments from the values.yml file:

```
﻿app:
  annotations: {}  # annotations to add on Promyze pods
```

But not yet on services, we'll work on it very soon :-)

**Comment by cteyton** [comment]
So to anwser you, currently we don't support annotations and labels for services neither labels for deployments. 
We'll work on it!
