### ISSUE TITLE
A pvc for the embeded database is created even if app.databaseEmbedded.enabled is false

### ISSUE THREAD

**Issue by jromelague** [promyze/helm-charts#9]
Hi,

Using the 0.3.4 version of the chart, if we set the `app.databaseEmbedded.enabled` value to `false`, a pvc for the embeded database is created. 
The condition to the pvc https://github.com/promyze/helm-charts/blob/main/charts/promyze/templates/pvc.yml must include a test on the `.Values.app.databaseEmbedded` value.
The workaround is to set both values to false.

Best regards,
Jérôme.

**Comment by cteyton** [comment]
Hi Jérôme,
Thanks for reporting this issue, indeed it does not make sense. 
I'll keep you updated.
